name: rotary
description: A new Flutter project.
version: 1.0.0+2
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  flutter_bloc: ^8.1.3
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  equatable: ^2.0.5
  google_sign_in: ^6.2.1
  flutter_login_facebook: ^1.6.2
  flutter_rating_bar: ^4.0.1
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  fluttertoast: ^8.2.4
  dots_indicator: ^3.0.0
  dio: ^5.4.0
  google_maps_flutter: ^2.5.3
  url_launcher: ^6.2.5
  intl: ^0.18.1
  country_pickers: ^2.0.0
  calendar_date_picker2: ^0.5.3
  flutter_slidable: ^0.6.0
  geocoding: ^3.0.0
  geocoder2: ^1.4.0
  firebase_auth: ^4.18.0
  flutter_easyloading: ^3.0.5

dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Poppins
      fonts: 
        - asset: assets/fonts/PoppinsBold.ttf
          weight: 700
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400
        - asset: assets/fonts/PoppinsSemiBold.ttf
          weight: 600
